In [1]:
cd E:\karthi_m\wind

E:\karthi_m\wind


In [2]:
import pandas as pd

In [3]:
da=pd.read_csv('data1.csv')

In [4]:
da.head()

windspeed  airdensity  amb_temp  nac_direction blds_pitchangle  rtr_rpm  \
0        9.1    1.162127        27           61.8         (-2,-4)     14.1   
1        9.6    1.162127        27           61.8         (-2,-4)     14.4   
2        9.6    1.162127        27           61.8         (-2,-4)     14.4   
3       11.2    1.162127        27           65.2     (-0.1,-1.9)     14.5   
4       11.4    1.162127        27           66.6     (-0.1,-1.9)     14.5   

   gen_rpm wtg_state  
0   1305.0        ok  
1   1336.0        ok  
2   1330.0        ok  
3   1345.0        ok  
4   1344.0        ok

In [5]:
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import LabelEncoder

In [6]:
y_ = da.apply(LabelEncoder().fit_transform)
y_.head()

windspeed  airdensity  amb_temp  nac_direction  blds_pitchangle  rtr_rpm  \
0         90           8         6            568                1      141   
1         95           8         6            568                1      144   
2         95           8         6            568                1      144   
3        111           8         6            602                0      145   
4        113           8         6            616                0      145   

   gen_rpm  wtg_state  
0     2805          3  
1     3036          3  
2     2982          3  
3     3124          3  
4     3114          3

In [7]:
x= y_.drop(['wtg_state'],axis=1)
y= y_['wtg_state']

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.25)

In [9]:
from sklearn.model_selection import cross_val_score, cross_val_predict
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [29]:
from sklearn.ensemble import AdaBoostClassifier

In [30]:
ada_clf = AdaBoostClassifier()

In [31]:
ada_clf.fit(X_train, y_train)

AdaBoostClassifier()

In [10]:
def print_score(clf, X_train, y_train, X_test, y_test, train=True):
    if train:
        print("Train Result:\n")
        print("accuracy score: {0:.4f}\n".format(accuracy_score(y_train, clf.predict(X_train))))
        print("Classification Report: \n {}\n".format(classification_report(y_train, clf.predict(X_train))))
        print("Confusion Matrix: \n {}\n".format(confusion_matrix(y_train, clf.predict(X_train))))

        res = cross_val_score(clf, X_train, y_train, cv=10, scoring='accuracy')
        print("Average Accuracy: \t {0:.4f}".format(np.mean(res)))
        print("Accuracy SD: \t\t {0:.4f}".format(np.std(res)))
        
    elif train==False:
        print("Test Result:\n")        
        print("accuracy score: {0:.4f}\n".format(accuracy_score(y_test, clf.predict(X_test))))
        print("Classification Report: \n {}\n".format(classification_report(y_test, clf.predict(X_test))))
        print("Confusion Matrix: \n {}\n".format(confusion_matrix(y_test, clf.predict(X_test))))

In [32]:
print_score(ada_clf, X_train, y_train, X_test, y_test, train=True)

Train Result:

accuracy score: 0.9032

Classification Report: 
               precision    recall  f1-score   support

           0       0.93      0.47      0.63      2926
           1       0.64      0.20      0.30      3129
           2       1.00      0.14      0.25        21
           3       0.89      0.99      0.94     33002
           4       1.00      1.00      1.00      6513

    accuracy                           0.90     45591
   macro avg       0.89      0.56      0.62     45591
weighted avg       0.89      0.90      0.88     45591


Confusion Matrix: 
 [[ 1387    15     0  1524     0]
 [   66   619     0  2444     0]
 [   18     0     3     0     0]
 [   16   328     0 32658     0]
 [    0     0     0     0  6513]]

Average Accuracy: 	 0.7365
Accuracy SD: 		 0.1703


In [33]:
print_score(ada_clf, X_train, y_train, X_test, y_test, train=False)

Test Result:

accuracy score: 0.9029



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Classification Report: 
               precision    recall  f1-score   support

           0       0.92      0.49      0.64       970
           1       0.63      0.20      0.31      1057
           2       0.00      0.00      0.00         8
           3       0.89      0.99      0.94     11018
           4       1.00      1.00      1.00      2145

    accuracy                           0.90     15198
   macro avg       0.69      0.54      0.58     15198
weighted avg       0.89      0.90      0.88     15198


Confusion Matrix: 
 [[  476     4     0   490     0]
 [   24   215     0   818     0]
 [    8     0     0     0     0]
 [    9   123     0 10886     0]
 [    0     0     0     0  2145]]



In [20]:
from sklearn.ensemble import RandomForestClassifier

In [11]:
from sklearn.ensemble import AdaBoostClassifier
ada_clf = AdaBoostClassifier(RandomForestClassifier())

In [12]:
ada_clf.fit(X_train, y_train)

AdaBoostClassifier(base_estimator=RandomForestClassifier())

In [17]:

from sklearn.model_selection import cross_val_score, cross_val_predict
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [ ]:
print_score(ada_clf, X_train, y_train, X_test, y_test, train=True)

Train Result:

accuracy score: 0.9191

Classification Report: 
               precision    recall  f1-score   support

           0       1.00      0.55      0.71      2926
           1       1.00      0.25      0.40      3129
           2       1.00      0.71      0.83        21
           3       0.90      1.00      0.95     33002
           4       1.00      1.00      1.00      6513

    accuracy                           0.92     45591
   macro avg       0.98      0.70      0.78     45591
weighted avg       0.93      0.92      0.90     45591


Confusion Matrix: 
 [[ 1611     0     0  1315     0]
 [    0   773     0  2356     0]
 [    0     0    15     6     0]
 [    0     0     0 33002     0]
 [    0     0     0    10  6503]]



In [21]:
print_score(ada_clf, X_train, y_train, X_test, y_test, train=False)

Test Result:

accuracy score: 0.9047

Classification Report: 
               precision    recall  f1-score   support

           0       0.98      0.47      0.64       970
           1       0.97      0.13      0.23      1057
           2       1.00      0.25      0.40         8
           3       0.88      1.00      0.94     11018
           4       1.00      1.00      1.00      2145

    accuracy                           0.90     15198
   macro avg       0.97      0.57      0.64     15198
weighted avg       0.91      0.90      0.88     15198


Confusion Matrix: 
 [[  457     3     0   510     0]
 [    5   140     0   912     0]
 [    2     0     2     4     0]
 [    0     2     0 11016     0]
 [    0     0     0    10  2135]]



In [22]:
from sklearn.ensemble import GradientBoostingClassifier

In [23]:
gbc_clf = GradientBoostingClassifier()
gbc_clf.fit(X_train, y_train)

GradientBoostingClassifier()

In [25]:
import numpy as np

In [26]:
print_score(gbc_clf, X_train, y_train, X_test, y_test, train=True)

Train Result:

accuracy score: 0.9407

Classification Report: 
               precision    recall  f1-score   support

           0       0.92      0.71      0.80      2926
           1       0.79      0.56      0.66      3129
           2       0.92      0.52      0.67        21
           3       0.94      0.99      0.96     33002
           4       1.00      1.00      1.00      6513

    accuracy                           0.94     45591
   macro avg       0.91      0.76      0.82     45591
weighted avg       0.94      0.94      0.94     45591


Confusion Matrix: 
 [[ 2075    84     0   767     0]
 [   88  1755     0  1286     0]
 [    7     2    11     1     0]
 [   90   377     1 32534     0]
 [    0     0     0     0  6513]]

Average Accuracy: 	 0.9384
Accuracy SD: 		 0.0029


In [27]:
print_score(gbc_clf, X_train, y_train, X_test, y_test, train=False) 

Test Result:

accuracy score: 0.9389

Classification Report: 
               precision    recall  f1-score   support

           0       0.93      0.70      0.80       970
           1       0.79      0.55      0.65      1057
           2       0.75      0.38      0.50         8
           3       0.94      0.99      0.96     11018
           4       1.00      1.00      1.00      2145

    accuracy                           0.94     15198
   macro avg       0.88      0.72      0.78     15198
weighted avg       0.94      0.94      0.93     15198


Confusion Matrix: 
 [[  679    25     0   266     0]
 [   20   584     1   452     0]
 [    3     1     3     1     0]
 [   28   131     0 10859     0]
 [    0     0     0     0  2145]]



In [15]:
import numpy as np

In [11]:
import xgboost as xgb

In [12]:
xgb_clf = xgb.XGBClassifier()

In [13]:
xgb_clf.fit(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\xgboost\sklearn.py:888: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[17:50:39] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=2, num_parallel_tree=1,
              objective='multi:softprob', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=None, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [16]:
print_score(xgb_clf, X_train, y_train, X_test, y_test, train=True)

Train Result:

accuracy score: 0.9589

Classification Report: 
               precision    recall  f1-score   support

           0       0.98      0.80      0.88      2897
           1       0.88      0.69      0.77      3145
           2       1.00      1.00      1.00        25
           3       0.96      0.99      0.97     33043
           4       1.00      1.00      1.00      6481

    accuracy                           0.96     45591
   macro avg       0.96      0.90      0.93     45591
weighted avg       0.96      0.96      0.96     45591


Confusion Matrix: 
 [[ 2327    20     0   550     0]
 [    8  2155     0   982     0]
 [    0     0    25     0     0]
 [   47   266     0 32730     0]
 [    0     0     0     0  6481]]

[18:09:20] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eva

C:\ProgramData\Anaconda3\lib\site-packages\xgboost\sklearn.py:888: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[18:09:34] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[18:09:47] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[18:09:57] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[18:10:06] WARNING: C:/Users/Administrator/workspace/xgboost-win64_

In [17]:
print_score(xgb_clf, X_train, y_train, X_test, y_test, train=False)

Test Result:

accuracy score: 0.9438

Classification Report: 
               precision    recall  f1-score   support

           0       0.91      0.76      0.83       999
           1       0.79      0.59      0.68      1041
           2       0.57      1.00      0.73         4
           3       0.95      0.98      0.96     10977
           4       1.00      1.00      1.00      2177

    accuracy                           0.94     15198
   macro avg       0.84      0.87      0.84     15198
weighted avg       0.94      0.94      0.94     15198


Confusion Matrix: 
 [[  759    31     3   206     0]
 [   21   619     0   401     0]
 [    0     0     4     0     0]
 [   58   134     0 10785     0]
 [    0     0     0     0  2177]]

