In [1]:
#Voting based Ensemble learning

In [1]:
cd E:\karthi_m\wind

E:\karthi_m\wind


In [2]:
import pandas as pd

In [3]:
da=pd.read_csv('data1.csv')

In [4]:
da.head()

windspeed  airdensity  amb_temp  nac_direction blds_pitchangle  rtr_rpm  \
0        9.1    1.162127        27           61.8         (-2,-4)     14.1   
1        9.6    1.162127        27           61.8         (-2,-4)     14.4   
2        9.6    1.162127        27           61.8         (-2,-4)     14.4   
3       11.2    1.162127        27           65.2     (-0.1,-1.9)     14.5   
4       11.4    1.162127        27           66.6     (-0.1,-1.9)     14.5   

   gen_rpm wtg_state  
0   1305.0        ok  
1   1336.0        ok  
2   1330.0        ok  
3   1345.0        ok  
4   1344.0        ok

In [5]:
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import LabelEncoder

In [7]:
y_ = da.apply(LabelEncoder().fit_transform)
y_.head()

windspeed  airdensity  amb_temp  nac_direction  blds_pitchangle  rtr_rpm  \
0         90           8         6            568                1      141   
1         95           8         6            568                1      144   
2         95           8         6            568                1      144   
3        111           8         6            602                0      145   
4        113           8         6            616                0      145   

   gen_rpm  wtg_state  
0     2805          3  
1     3036          3  
2     2982          3  
3     3124          3  
4     3114          3

In [8]:
x= y_.drop(['wtg_state'],axis=1)
y= y_['wtg_state']

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.25)

In [10]:
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB()

In [11]:
fit_=clf.fit(X_train,y_train)

In [12]:
y_pred=fit_.predict(X_test)

In [13]:
#import the metrics class
from sklearn import metrics
cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
cnf_matrix

array([[ 319,   83,   11,  255,  317],
       [  12,  854,    0,  157,   11],
       [   0,    0,    5,    1,    2],
       [1728, 4158,    0, 5073,  103],
       [ 391,   31,    3,   87, 1597]], dtype=int64)

In [14]:
# Fitting Classifier to the Training Set
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion='entropy',max_depth=3, random_state=42)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=3, random_state=42)

In [15]:
# Model performance on training set
y_pred=classifier.predict(X_test)

from sklearn import metrics
from sklearn.metrics import confusion_matrix, classification_report

accuracy = metrics.accuracy_score(y_test, y_pred)
print("Accuracy: {:.2f}".format(accuracy))
cm=confusion_matrix(y_test,y_pred)
print('Confusion Matrix: \n', cm)

Accuracy: 0.89
Confusion Matrix: 
 [[  424     0     1   560     0]
 [   10     0     0  1024     0]
 [    1     0     4     3     0]
 [    0     0     0 11062     0]
 [    0     0     0     0  2109]]


In [16]:
#Importing Libraries
import numpy as np
from sklearn.ensemble import RandomForestClassifier

In [17]:
# Fitting Random Forest Classification to the Training set
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 42)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=42)

In [18]:
y_pred=classifier.predict(X_test)

In [21]:
# Model performance on training set
y_pred_train =classifier.predict(X_test)

from sklearn import metrics
from sklearn.metrics import confusion_matrix, classification_report

accuracy = metrics.accuracy_score(y_test, y_pred_train)
cm=confusion_matrix(y_test,y_pred_train)
print('Confusion Matrix: \n', cm)

Confusion Matrix: 
 [[  711    39     0   235     0]
 [   32   636     0   366     0]
 [    2     0     6     0     0]
 [   93   256     0 10713     0]
 [    0     0     0     0  2109]]


In [22]:
#Defining Hybrid Ensemble Learning Model
estimators = []

#Defining 5 Naive bayes Models
model11 = MultinomialNB()
estimators.append(('NB1', model11))
model12 = MultinomialNB()
estimators.append(('NB2', model12))
model13 = MultinomialNB()
estimators.append(('NB3', model13))
model14 = MultinomialNB()
estimators.append(('NB4', model14))
model15 = MultinomialNB()
estimators.append(('NB5', model15))


In [23]:
#Defining 5 Decision Tree Classifiers
model16 = DecisionTreeClassifier(criterion='entropy',max_depth = 3)
estimators.append(('cart1', model16))
model17 = DecisionTreeClassifier(criterion='entropy',max_depth = 4)
estimators.append(('cart2', model17))
model18 = DecisionTreeClassifier(criterion='entropy',max_depth = 5)
estimators.append(('cart3', model18))
model19 = DecisionTreeClassifier(criterion='entropy',max_depth = 2)
estimators.append(('cart4', model19))
model20 = DecisionTreeClassifier(criterion='entropy',max_depth = 3)
estimators.append(('cart5', model20))

In [24]:
#Defining 5 Random forest Classifiers
model21 = RandomForestClassifier(n_estimators = 10, criterion = 'entropy')
estimators.append(('rf1', model21))
model22 = RandomForestClassifier(n_estimators = 11, criterion = 'entropy')
estimators.append(('rf2', model22))
model23 = RandomForestClassifier(n_estimators = 12, criterion = 'entropy')
estimators.append(('rf3', model23))
model24 = RandomForestClassifier(n_estimators = 14, criterion = 'entropy')
estimators.append(('rf4', model24))
model25 = RandomForestClassifier(n_estimators = 15, criterion = 'entropy')
estimators.append(('rf5', model25))

In [25]:
from sklearn.ensemble import VotingClassifier
# Defining the ensemble model
ensemble = VotingClassifier(estimators)
ensemble.fit(X_train, y_train)
y_pred = ensemble.predict(X_test)


In [26]:
#Confisuin matrix
ensembler_cm = confusion_matrix(y_test, y_pred)

In [27]:
ensembler_cm

array([[  607,    16,     0,   362,     0],
       [   15,   568,     0,   451,     0],
       [    3,     0,     4,     1,     0],
       [   36,   189,     0, 10837,     0],
       [    0,     0,     0,     0,  2109]], dtype=int64)

In [28]:
from sklearn import model_selection
#Cross-Validation
seed = 7
kfold = model_selection.KFold(n_splits=10, random_state=seed)
results = model_selection.cross_val_score(ensemble, X_train, y_train, cv=kfold)
print(results.mean())

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:293: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  warnings.warn(


0.9277927504107935
